### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by nsrwork** [nsrwork/crypto-trading-history#1]
https://github.com/nsrwork/crypto-trading-history/blob/fc9a1254dc7d5888cdfac96fc7311d5202c770a6/src/aggregator.js#L8

**Comment by Konders** [comment]
Do you mean smth like that?
`if(raw.time < trade.getStartDate()) {
        continue;
      }`

**Comment by nsrwork** [comment]
Very poor issue description. My fault, sorry. 
Open positions(trades) are skipped in the reports, and this issue is just to display them, too, not skip.
